### ISSUE TITLE
Different bug introduced

### ISSUE THREAD

**Issue by SandPoot** [sapegin/vscode-new-file-now#2]
Cannot confirm creation

![Code_Std37H8Sxs](https://github.com/sapegin/vscode-new-file-now/assets/43283559/907041b7-a5da-4d5c-8abf-227723fe061c)

Fixed by [this commit](https://github.com/sapegin/vscode-new-file-now/commit/e13f59e20c835708e941b5a77fb363ad2df2f547)

**Comment by sapegin** [comment]
Can you post the logs?

**Comment by SandPoot** [comment]
![image](https://github.com/sapegin/vscode-new-file-now/assets/43283559/8562a656-1f6e-4355-ba6c-749c6d1a5ed2)
There's not exactly any errors here, but i simply cannot continue with the operation, it appears that the suggestion no longer updates like it did before

**Comment by sapegin** [comment]
Yeah, and there isn't much happening here, so I can't really guess what might be wrong without being able to debug the code:

https://github.com/sapegin/vscode-new-file-now/blob/65d85a7d4604d059735562f554e394ddbdc966e1/src/Picker.ts#L35-L37

https://github.com/sapegin/vscode-new-file-now/blob/65d85a7d4604d059735562f554e394ddbdc966e1/src/Picker.ts#L45-L48 

And somehow here the `value` is still empty: 

https://github.com/sapegin/vscode-new-file-now/blob/65d85a7d4604d059735562f554e394ddbdc966e1/src/Picker.ts#L98

**Comment by SandPoot** [comment]
I'd say maybe something is up with the regex op? But I'm not really good at this.

**Comment by sapegin** [comment]
You're absolutely right, I also thought of that and indeed `\` needs to be escaped...

**Comment by SandPoot** [comment]
Thank you very much for fixing it, this kind of stuff should be on base VSC.

**Comment by sapegin** [comment]
Yay, glad it finally works! 🌮
